# Generated by Django 4.2.5 on 2023-10-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount_to_save', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_saved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
